// 課程產品資料（來源：tidyman.com.tw/tidylist/）

export const mockCategories = [
  { id: '1', name: '初階整聊', slug: 'beginner', sortOrder: 1 },
  { id: '2', name: '中階整聊', slug: 'intermediate', sortOrder: 2 },
  { id: '3', name: '整聊師認證課程', slug: 'certification', sortOrder: 3 },
  { id: '4', name: '人生整聊學院', slug: 'life-academy', sortOrder: 4 },
  { id: '5', name: '軟裝服務', slug: 'soft-deco', sortOrder: 5 },
]

export const mockProducts = [
  {
    id: '1',
    sku: 'L1-001',
    name: '整聊師培訓課程 L1初階實戰篇',
    slug: 'course-l1',
    shortDescription: '從零開始學整理，建立整聊師的核心基礎技能，適合想改變生活空間的你。',
    originalPrice: 4000,
    salePrice: 4000,
    ambassadorDiscount: 200,
    stock: 20,
    allowBackorder: false,
    mainImage: '/images/products/course-l1.png',
    gallery: [] as string[],
    commissionType: 'PERCENTAGE' as 'PERCENTAGE' | 'FIXED',
    commissionValue: 10,
    defaultShareText: '推薦給你整聊L1初階課程！學整理從這裡開始 💪\n{link}',
    isActive: true,
    isFeatured: true,
    categories: [{ name: '初階整聊', slug: 'beginner' }],
  },
  {
    id: '2',
    sku: 'L2-001',
    name: '整聊師培訓課程 L2中階修煉篇',
    slug: 'course-l2',
    shortDescription: '深化整理技法與心法，學習如何協助他人建立系統化的整理習慣。',
    originalPrice: 16000,
    salePrice: 16000,
    ambassadorDiscount: 500,
    stock: 15,
    allowBackorder: false,
    mainImage: '/images/products/course-l2.png',
    gallery: [] as string[],
    commissionType: 'PERCENTAGE' as 'PERCENTAGE' | 'FIXED',
    commissionValue: 10,
    defaultShareText: '推薦整聊L2中階課程，整理功力大升級！\n{link}',
    isActive: true,
    isFeatured: true,
    categories: [{ name: '中階整聊', slug: 'intermediate' }],
  },
  {
    id: '3',
    sku: 'L3-001',
    name: '整聊師培訓課程 L3榮耀授袍簽約',
    slug: 'course-l3',
    shortDescription: '完成中階課程的最終認證，正式取得整聊師資格，成為認證整聊師。',
    originalPrice: 2000,
    salePrice: 2000,
    ambassadorDiscount: 0,
    stock: 20,
    allowBackorder: false,
    mainImage: '/images/products/course-l3.png',
    gallery: [] as string[],
    commissionType: 'PERCENTAGE' as 'PERCENTAGE' | 'FIXED',
    commissionValue: 10,
    defaultShareText: null as string | null,
    isActive: true,
    isFeatured: false,
    categories: [{ name: '中階整聊', slug: 'intermediate' }],
  },
  {
    id: '4',
    sku: 'BUNDLE-L1L2',
    name: '【初＋中】整聊技法心法一次學',
    slug: 'course-bundle-l1l2',
    shortDescription: '初階 + 中階課程套組，一次學完整聊技法與心法，超值組合價更划算。',
    originalPrice: 20000,
    salePrice: 18000,
    ambassadorDiscount: 500,
    stock: 15,
    allowBackorder: false,
    mainImage: '/images/products/course-bundle-l1l2.png',
    gallery: [] as string[],
    commissionType: 'PERCENTAGE' as 'PERCENTAGE' | 'FIXED',
    commissionValue: 10,
    defaultShareText: '推薦整聊初中階套組，一次學完超值！\n{link}',
    isActive: true,
    isFeatured: true,
    categories: [{ name: '中階整聊', slug: 'intermediate' }],
  },
  {
    id: '5',
    sku: 'BUNDLE-FULL',
    name: '【初＋中＋認證測驗】直接成為整聊師',
    slug: 'course-bundle-full',
    shortDescription: '初階＋中階＋認證測驗三合一，最快捷徑直接取得整聊師認證。',
    originalPrice: 22000,
    salePrice: 20000,
    ambassadorDiscount: 500,
    stock: 15,
    allowBackorder: false,
    mainImage: '/images/products/course-bundle-full.png',
    gallery: [] as string[],
    commissionType: 'PERCENTAGE' as 'PERCENTAGE' | 'FIXED',
    commissionValue: 10,
    defaultShareText: '最快成為整聊師的方法！\n{link}',
    isActive: true,
    isFeatured: false,
    categories: [{ name: '整聊師認證課程', slug: 'certification' }],
  },
  {
    id: '6',
    sku: 'CAMP-001',
    name: '整聊實作訓練營｜最硬派整理訓練課',
    slug: 'course-training-camp',
    shortDescription: '最紮實的整理實作訓練，透過密集實戰演練，讓整理能力脫胎換骨。',
    originalPrice: 20000,
    salePrice: 20000,
    ambassadorDiscount: 500,
    stock: 10,
    allowBackorder: false,
    mainImage: '/images/products/course-training-camp.png',
    gallery: [] as string[],
    commissionType: 'PERCENTAGE' as 'PERCENTAGE' | 'FIXED',
    commissionValue: 10,
    defaultShareText: null as string | null,
    isActive: true,
    isFeatured: false,
    categories: [{ name: '中階整聊', slug: 'intermediate' }],
  },
  {
    id: '7',
    sku: 'MOVE-001',
    name: '搬家手實作1日課',
    slug: 'course-moving',
    shortDescription: '一日密集課程，學習搬家整理的實戰技巧，讓搬家不再是噩夢。',
    originalPrice: 3000,
    salePrice: 3000,
    ambassadorDiscount: 0,
    stock: 0,
    allowBackorder: false,
    mainImage: '/images/products/course-moving.png',
    gallery: [] as string[],
    commissionType: 'PERCENTAGE' as 'PERCENTAGE' | 'FIXED',
    commissionValue: 10,
    defaultShareText: null as string | null,
    isActive: true,
    isFeatured: false,
    categories: [{ name: '初階整聊', slug: 'beginner' }],
  },
  {
    id: '8',
    sku: 'AMB-2025',
    name: '【整聊高階】2025品牌大使培訓營',
    slug: 'course-ambassador-2025',
    shortDescription: '三天兩夜密集培訓，完整品牌大使技能養成，開啟整聊師資格與副業收入。',
    originalPrice: 35000,
    salePrice: 27000,
    ambassadorDiscount: 1000,
    stock: 12,
    allowBackorder: false,
    mainImage: '/images/products/course-ambassador-2025.png',
    gallery: [] as string[],
    commissionType: 'FIXED' as 'PERCENTAGE' | 'FIXED',
    commissionValue: 2000,
    defaultShareText: '2025整聊品牌大使培訓營開放報名！\n{link}',
    isActive: true,
    isFeatured: true,
    categories: [{ name: '整聊師認證課程', slug: 'certification' }],
  },
  {
    id: '9',
    sku: 'SOFT-001',
    name: '【整聊高階】軟裝師認證課程',
    slug: 'course-soft-deco',
    shortDescription: '成為軟裝師，從整理延伸到空間佈置設計，打造質感生活空間的完整訓練。',
    originalPrice: 30000,
    salePrice: 30000,
    ambassadorDiscount: 500,
    stock: 0,
    allowBackorder: false,
    mainImage: '/images/products/course-soft-deco.jpg',
    gallery: [] as string[],
    commissionType: 'FIXED' as 'PERCENTAGE' | 'FIXED',
    commissionValue: 3000,
    defaultShareText: null as string | null,
    isActive: true,
    isFeatured: false,
    categories: [{ name: '軟裝服務', slug: 'soft-deco' }],
  },
  {
    id: '10',
    sku: 'FASHION-001',
    name: '穿搭諮詢師實戰班',
    slug: 'course-fashion',
    shortDescription: '從衣櫃整理到穿搭風格建立，成為專業穿搭諮詢師的完整訓練課程。',
    originalPrice: 12000,
    salePrice: 12000,
    ambassadorDiscount: 300,
    stock: 0,
    allowBackorder: false,
    mainImage: '/images/products/course-fashion.png',
    gallery: [] as string[],
    commissionType: 'PERCENTAGE' as 'PERCENTAGE' | 'FIXED',
    commissionValue: 10,
    defaultShareText: null as string | null,
    isActive: true,
    isFeatured: false,
    categories: [{ name: '人生整聊學院', slug: 'life-academy' }],
  },
  {
    id: '11',
    sku: 'FASHION-ONLINE-001',
    name: '【穿搭線上體驗課】衣櫃斷捨離！打造美好穿搭人生',
    slug: 'course-fashion-online',
    shortDescription: '線上課程，學習衣櫃斷捨離與穿搭搭配技巧，小預算打造高質感衣著。',
    originalPrice: 2200,
    salePrice: 1280,
    ambassadorDiscount: 100,
    stock: 50,
    allowBackorder: false,
    mainImage: '/images/products/course-fashion-online.png',
    gallery: [] as string[],
    commissionType: 'FIXED' as 'PERCENTAGE' | 'FIXED',
    commissionValue: 200,
    defaultShareText: '線上穿搭體驗課，超值！\n{link}',
    isActive: true,
    isFeatured: false,
    categories: [{ name: '人生整聊學院', slug: 'life-academy' }],
  },
]

export type MockProduct = typeof mockProducts[0]
