// 開發用假資料，正式環境從資料庫讀取

export const mockCategories = [
  { id: '1', name: '初階整聊', slug: 'beginner', sortOrder: 1 },
  { id: '2', name: '中階整聊', slug: 'intermediate', sortOrder: 2 },
  { id: '3', name: '高階整聊', slug: 'advanced', sortOrder: 3 },
  { id: '4', name: '人生整聊學院', slug: 'life-coaching', sortOrder: 4 },
  { id: '5', name: '軟裝服務', slug: 'interior', sortOrder: 5 },
]

export const mockProducts = [
  {
    id: '1',
    sku: 'GUDO-B001',
    name: '整聊初階認證課程',
    slug: 'online_basic',
    shortDescription: '從零開始學習整理與溝通的基礎技能，適合想要改變生活的你',
    originalPrice: 35000,
    salePrice: 27000,
    ambassadorDiscount: 500,
    stock: 20,
    allowBackorder: false,
    mainImage: '/images/products/basic-course.jpg',
    gallery: [] as string[],
    commissionType: 'PERCENTAGE' as 'PERCENTAGE' | 'FIXED',
    commissionValue: 10,
    defaultShareText: '這是我上過的整聊課程，對我非常有幫助！\n如果你也想學習整理與溝通，這邊下單可以透過我的推薦碼享有折扣唷～\n{link}',
    isActive: true,
    isFeatured: true,
    categories: [{ name: '初階整聊', slug: 'beginner' }],
  },
  {
    id: '2',
    sku: 'GUDO-I001',
    name: '整聊中階進階課程',
    slug: 'online_intermediate',
    shortDescription: '深化整理技能，學習如何協助他人建立系統化的整理習慣',
    originalPrice: 48000,
    salePrice: 38000,
    ambassadorDiscount: 500,
    stock: 15,
    allowBackorder: false,
    mainImage: '/images/products/intermediate-course.jpg',
    gallery: [] as string[],
    commissionType: 'PERCENTAGE' as 'PERCENTAGE' | 'FIXED',
    commissionValue: 12,
    defaultShareText: null as string | null,
    isActive: true,
    isFeatured: true,
    categories: [{ name: '中階整聊', slug: 'intermediate' }],
  },
  {
    id: '3',
    sku: 'GUDO-A001',
    name: '整聊高階師資培訓',
    slug: 'online_advanced',
    shortDescription: '成為整聊認證師資，開啟你的整理顧問事業',
    originalPrice: 88000,
    salePrice: 72000,
    ambassadorDiscount: 1000,
    stock: 8,
    allowBackorder: false,
    mainImage: '/images/products/advanced-course.jpg',
    gallery: [] as string[],
    commissionType: 'FIXED' as 'PERCENTAGE' | 'FIXED',
    commissionValue: 5000,
    defaultShareText: null as string | null,
    isActive: true,
    isFeatured: false,
    categories: [{ name: '高階整聊', slug: 'advanced' }],
  },
  {
    id: '4',
    sku: 'GUDO-L001',
    name: '2025 品牌大使培訓營（6月梯次）',
    slug: 'ambassador-camp-2025-june',
    shortDescription: '三天兩夜密集培訓，完整品牌大使技能養成課程',
    originalPrice: 15800,
    salePrice: 12800,
    ambassadorDiscount: 300,
    stock: 0,
    allowBackorder: false,
    mainImage: '/images/products/ambassador-camp.jpg',
    gallery: [] as string[],
    commissionType: 'PERCENTAGE' as 'PERCENTAGE' | 'FIXED',
    commissionValue: 10,
    defaultShareText: null as string | null,
    isActive: true,
    isFeatured: false,
    categories: [{ name: '人生整聊學院', slug: 'life-coaching' }],
  },
  {
    id: '5',
    sku: 'GUDO-L002',
    name: '2025 品牌大使培訓營（9月梯次）',
    slug: 'ambassador-camp-2025-sept',
    shortDescription: '三天兩夜密集培訓，完整品牌大使技能養成課程',
    originalPrice: 15800,
    salePrice: 12800,
    ambassadorDiscount: 300,
    stock: 12,
    allowBackorder: false,
    mainImage: '/images/products/ambassador-camp.jpg',
    gallery: [] as string[],
    commissionType: 'PERCENTAGE' as 'PERCENTAGE' | 'FIXED',
    commissionValue: 10,
    defaultShareText: null as string | null,
    isActive: true,
    isFeatured: false,
    categories: [{ name: '人生整聊學院', slug: 'life-coaching' }],
  },
  {
    id: '6',
    sku: 'GUDO-S001',
    name: '居家軟裝顧問服務',
    slug: 'interior-consulting',
    shortDescription: '專業居家整理顧問到府服務，打造屬於你的理想生活空間',
    originalPrice: 8800,
    salePrice: 6800,
    ambassadorDiscount: 200,
    stock: 5,
    allowBackorder: false,
    mainImage: '/images/products/interior-service.jpg',
    gallery: [] as string[],
    commissionType: 'FIXED' as 'PERCENTAGE' | 'FIXED',
    commissionValue: 500,
    defaultShareText: null as string | null,
    isActive: true,
    isFeatured: false,
    categories: [{ name: '軟裝服務', slug: 'interior' }],
  },
]

export type MockProduct = typeof mockProducts[0]
